version: '3.9'

services:
  nest:
    image: pyo00/qterview:version3
    ports:
      - 80:3000
    environment:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_USER: ${{secrets.DB_USER}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      MONGODB: ${{secrets.MONGODB}}
      OPENAI_EMAIL: ${{secrets.OPENAI_EMAIL}}
      OPENAI_PASSWORD: ${{secrets.OPENAI_PASSWORD}}
      OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
      NOPECHAKE: ${{secrets.NOPECHAKE}}
      KEY: ${{secrets.KEY}}
      CERT: ${{secrets.CERT}}
      BUILD_ENV: ${{secrets.BUILD_ENV}}
